// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgaoflwtzmtnpuzzihdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnYW9mbHd0em10bnB1enppaGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Nzk1OTAsImV4cCI6MjA3MzA1NTU5MH0.TsrN9RbLUMbPzuQajJMS3o_TPtKIs8zM4xtirjhiMJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});